### ISSUE TITLE
Move LoginForm.js and LoginForm.css out of folder

### ISSUE THREAD

**Issue by mdew192837** [huiyie/hacktober-learn-react#12]
When I try to import the component using 

`import LoginForm from '../components/LoginForm.js';`

it throws me the following error:

`Module not found: You attempted to import ../components/LoginForm.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported. You can either move it inside src/, or add a symlink to it from project's node_modules/.`

Should we move it outside of the folder?

I've never really touched React, so I'm not sure how to use the component.

**Comment by huiyie** [comment]
I think LoginForm is in a subfolder nested within src/ so maybe you could try doing
```import LoginForm from './components/LoginForm.js'; ``` instead?
Let me know if this works for you 👍

**Comment by mdew192837** [comment]
Yep, it does!
