### ISSUE TITLE
Sidebar for navigation, with icons for each label

### ISSUE THREAD

**Issue by huiyie** [huiyie/hacktober-learn-react#5]

**Comment by huiyie** [comment]
Maybe imagine that the labels we want are "Home", "School", "Social", "Calendar" and "Settings"

**Comment by nitish24p** [comment]
Can i pick this up?

**Comment by yussan** [comment]
you are so fast @nitish24p , ok go ahead

**Comment by huiyie** [comment]
Nice, looking forward to this!

**Comment by nitish24p** [comment]
Does it have to be implemented from scratch or a sidebar component library will suffice?

**Comment by huiyie** [comment]
I think either case is interesting (e.g. your choice of library or way to implement it from scratch). I'm open to either!

**Comment by TheCodeArtist** [comment]
@nitish24p in case you are planning to use component, how about [**this**](http://negomi.github.io/react-burger-menu/)?...

**Comment by nitish24p** [comment]
@TheCodeArtist looks really sleek..

**Comment by huiyie** [comment]
@TheCodeArtist that looks amazing! love the CSS transitions and overall look and feel of the component

**Comment by beatfreaker** [comment]
@nitish24p you are just creating menu component or you will be integrating it with routing ?
@huiyie can i implement basic routing to this application ? we can later integrate it with navigation menu as well.

**Comment by huiyie** [comment]
@beatfreaker that's cool, I was thinking of routing as a part of this learning exercise for React too 👍 go ahead!

**Comment by beatfreaker** [comment]
@huiyie created PR [#14](https://github.com/huiyie/hacktober-learn-react/pull/14)
Please review it, let me know if anything needs to be updated.

**Comment by beatfreaker** [comment]
@nitish24p if you are not working on this, can i take i this ?

**Comment by nitish24p** [comment]
Yes. I have been hospitalised due to an illness you can pick this up

**Comment by beatfreaker** [comment]
@nitish24p get well soon bud
